name: run python scripts
on: [push]
jobs:
  python-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: chnage permissions
        run: chmod u+x test.py
      - name: install dependency
        run: pip3 install -r "requirements.txt"
      - name: run scripts
        run: ./test.py